image: Visual Studio 2017

install:
  - cmd: git submodule update --init --recursive

build: off

build_script:
  - cmd: cd Keyczar
  - cmd: msbuild /t:restore
  - cmd: msbuild

test:
  categories:
    except:
      - Performance

artifacts:
  - path: '**\bin\*\*.nupkg'

skip_branch_with_pr: true