image: Visual Studio 2017

install:
  - cmd: git submodule update --init --recursive

build: off

build_script:
  - cmd: cd Keyczar
  - cmd: msbuild /t:restore /p:Configuration=Release
  - cmd: msbuild /p:VersionSuffix="alpha%APPVEYOR_BUILD_NUMBER%" /p:Configuration=Release
  - cmd: .\packages\nunit.runners\2.6.1\tools\nunit-console.exe -noxml -nodots -labels -stoponerror KeyczarTest\bin\Release\net40\KeyczarTest.dll -include=Create

test:
  categories:
    except:
      - Performance
      - Create

skip_branch_with_pr: true

artifacts:
  - path: Keyczar\Keyczar\bin\Release\*.nupkg
    name: Keyczar
  - path: Keyczar\KeyczarTool.Minified\bin\Release\*.nupkg
    name: KeyczarTool

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/keyczar-dotnet-ci/api/v2/package
    api_key:
      secure: qeW4Vpu7ZxccbJAZz215XBKpSTlIXEyZTfi/r+gmEGRxC/zsxHkBexycRjKbfptZ
    skip_symbols: false
    symbol_server: https://www.myget.org/F/keyczar-dotnet-ci/symbols/api/v2/package
    artifact: Keyczar
