image: Visual Studio 2017

install:
  - cmd: git submodule update --init --recursive

configuration: Debug

build: off

environment:
  vsuffix: alpha$(APPVEYOR_BUILD_NUMBER)

before_build:
  - cmd: cd Keyczar
  - cmd: msbuild /t:restore /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

build_script:
  - cmd: msbuild /p:Configuration=%configuration% /p:VersionSuffix="%vsuffix%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

before_test:
  - cmd: nunit-console -noxml -nodots -labels -stoponerror KeyczarTest\bin\%configuration%\net40\KeyczarTest.dll -include=Create

test:
  categories:
    except:
      - Performance
      - Create

artifacts:
  - path: Keyczar\Keyczar\bin\$(configuration)\*.nupkg
    name: Keyczar
  - path: Keyczar\KeyczarTool.Minified\bin\$(configuration)\*.nupkg
    name: KeyczarTool

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/keyczar-dotnet-ci/api/v2/package
    api_key:
      secure: qeW4Vpu7ZxccbJAZz215XBKpSTlIXEyZTfi/r+gmEGRxC/zsxHkBexycRjKbfptZ
    skip_symbols: false
    symbol_server: https://www.myget.org/F/keyczar-dotnet-ci/symbols/api/v2/package

  - provider: GitHub
    artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
    draft: true
    prerelease: true
    on:
      appveyor_repo_tag: true       # deploy on tag push only

for:
  branches:
      only:
        - /v.*-beta/
  environment:
    vsuffix: beta$(APPVEYOR_BUILD_NUMBER)


