image: Visual Studio 2017

install:
  - cmd: git submodule update --init --recursive

configuration: Debug

build: off

before_build:
  - cmd: cd Keyczar
  - cmd: msbuild /t:restore

build_script:
  - cmd: msbuild /p:Configuration=%configuration% /p:VersionSuffix="alpha%APPVEYOR_BUILD_NUMBER%"

before_test:
  - cmd: .\packages\nunit.runners\2.6.1\tools\nunit-console.exe -noxml -nodots -labels -stoponerror KeyczarTest\bin\%configuration%\net40\KeyczarTest.dll -include=Create

test:
  categories:
    except:
      - Performance
      - Create

artifacts:
  - path: Keyczar\Keyczar\bin\$(configuration)\*.nupkg
    name: Keyczar
  - path: Keyczar\KeyczarTool.Minified\bin\$(configuration)\*.nupkg
    name: KeyczarTool

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/keyczar-dotnet-ci/api/v2/package
    api_key:
      secure: qeW4Vpu7ZxccbJAZz215XBKpSTlIXEyZTfi/r+gmEGRxC/zsxHkBexycRjKbfptZ
    skip_symbols: false
    symbol_server: https://www.myget.org/F/keyczar-dotnet-ci/symbols/api/v2/package

  - provider: GitHub
    artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
    draft: true
    prerelease: true
    on:
      appveyor_repo_tag: true       # deploy on tag push only


for:
-
  branches:
    only:
      - /v[\d,.]*/

  configuration: Release
  
  build_script:
    - cmd: msbuild /p:Configuration=%configuration%

- 
  branches:
    only:
      - /v[\d,.]*-beta/
  
  build_script:
    - cmd: msbuild /p:Configuration=%configuration% /p:VersionSuffix="beta%APPVEYOR_BUILD_NUMBER%"


