# Travis-CI Build for keyczar-dotnet 
# see travis-ci.org for details

language: c

install:
 # Make sure mono is installed,
 # pipe stdout to dev/null because qq is still too chatty
 - sudo apt-get update -qq > /dev/null
 - sudo apt-get install -qq mono-devel > /dev/null
script:
 - cd Keyczar/
 - .ci/PreXbuild.sh
 - ./mono-build.sh 
 - .ci/PostXbuild.sh 

branches:
 only:
  - master
  - stable
