# Travis-CI Build for keyczar-dotnet 
# see travis-ci.org for details

language: csharp
solution: Keyczar/Keyczar.sln

mono:
  - latest
  - 3.12.0
  - 3.10.0
  - 2.10.8

script:
 - cd Keyczar/
 - xbuild 
 - .ci/RunTests.sh
