# Travis-CI Build for keyczar-dotnet 
# see travis-ci.org for details

language: csharp
solution: Keyczar/Keyczar.sln

env:		
  - EnableNuGetPackageRestore=true 

mono:
  - latest
  - 3.12.0
  - 3.10.0

script:
 - cd Keyczar/
 - xbuild 
 - .ci/RunTests.sh
